config/routes.rb
Omrails::Application.routes.draw do
  get "users/show"
  resources :pins

  devise_for :users
  match 'users/:id' => 'users#show', as: :user, via: [:get, :post]
 
  devise_scope :user do
  match '/users/sign_out' => 'sessions#destroy', via: [:get, :delete]
end
  get 'about' => 'pages#about'
  root :to => 'pins#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base

	validates :description, presence: true
	validates :user_id, presence: true
	
	belongs_to :user
	has_attached_file :image, styles: { medium: "320x240>"}


def image_remote_url=(url_value)
 		self.image = URI.parse(url_value) unless url_value.blank?
 		super

	validates_attachment :image, presence: true,
						 	content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']},
						 	size: { less_than: 5.megabytes }

	


 	
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :pins
validates :user_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

 	def configure_permitted_parameters
   		devise_parameter_sanitizer.for(:sign_up) << :name
   		devise_parameter_sanitizer.for(:account_update) << :name
 	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def action
  end
end

app/controllers/pins_controller.rb
  # GET /pins/1/edit
  class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order("created_at DESC").page(params[:page]).per_page(20)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new' 
    end
  end

  # PATCH/PUT /pins/1
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /pins/1
  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorised to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/controllers/users_controller.rb
	class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@pins = @user.pins.page(params[:page]).per_page(20)
  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
		<small> 
			<%= link_to "One Month Rails", "http://onemonthrails.com" %>
			by <%= link_to "Mattan Greffel", "http://mattangriffel.com" %>

		</small>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar navbar-fixed-top" role="navigation">
  <div class="container-fluid"> 
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header"> 
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
<%= link_to "One Month Rails", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in?(:user)  %>
          <li> <%= link_to "Add +", new_pin_path %></li>
          <li> <%= link_to "Edit Profile", destroy_user_session_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %>
          <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
 
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>One Month Rails</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag :all %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>
	<%= yield %>
		<%= render 'layouts/footer' %>

	</div>

	</body>
</html>

app/views/pages/_home.html.erb
<% if signed_in?(:user) %>
 <h1> You're logged in!</h1>
 <% else %>
<div class="hero-unit">

<h1>Welcome to One Month Rails!</h1>
<p>
	You've found the home page for the
	<%= link_to "One Month Rails", "http://onemonthrails.com" %>
	application
</p>
<p>
	<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
</p>
</div>
<% end %>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	<%= link_to "One Month Rails", "http://onemonthrails.com" %>
	is a project to teach
	<%= link_to "Ruby on Rails", "http://rubyonrails.org" %>
	in one month. This is the sample application
</p>

app/views/pages/home.html.erb
<% if signed_in?(:user) %>
 <h1> You're logged in!</h1>
 <% else %>
<div class="hero-unit">

<h1>Welcome to One Month Rails!</h1>
<p>
	You've found the home page for the
	<%= link_to "One Month Rails", "http://onemonthrails.com" %>
	application
</p>
<p>
	<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
</p>
</div>
<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload an image" %>
  <%= f.input :image_remote_url, label: "or enter URL" %>
  	<%= f.input :description, as: :text, input_html: { rows: "3"} %>


  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pins.html.erb
<div class="box">
  <%= link_to (image_tag pin.image(:medium)), pin %>
  <p class="description">
    <%= pin.description %>
  </p>
  <p>
    <strong>
      Posted by <%= link_to pin.user.name, pin.user %>
    </strong>
  </p>
  <% if current_user == pin.user %>
    <p>
      <%= link_to 'Edit', edit_pin_path(pin) %>
      <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
</div>
              

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins">
<%= render 'pins' %>
</div>

<%= will_paginate @pins %>
  

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class ="well">
			<%= image_tag @pin.image %>
		<p>
			<%@pin.description %>
		</p>
			<p>
			<%@pin.user.name %>
		</p>
		<% if @pin.user == current_user %>
			<%= link_to 'Edit', edit_pin_path(@pin) %> |
		<% end %>
			<%= link_to 'Back', pins_path %>
		
	</div>
	</div>	

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<div id="pins">
	<%= render @pins %>
</div>

<%= will_paginate @pins %>